name: Nail Disease CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Model from Google Drive
      run: |
        pip install gdown
        gdown https://drive.google.com/uc?id=1Vs7AgzN4mJfBYfLYhNXF7AAROq9SPCz1

    - name: Rename Model
      run: |
        mv *.h5 vgg-16-nail-disease.h5

    - name: Run Basic Test
      run: |
        echo "CI Pipeline Working Successfully!"
